apiVersion: v1
kind: Pod
metadata:
  labels:
    run: adapter-pod
  name: adapter-pod
spec:
  containers:
  - image: busybox
    name: adapter-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
