apiVersion: v1
kind: Pod
metadata:
  labels:
    run: sidecar-pod
  name: sidecar-pod
spec:
  containers:
  - image: nginx
    name: app
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  - name: logger
    image: busybox
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
    command: ["/bin/sh", "-c", "tail -f /var/log/nginx/access.log"]
  volumes:
  - name: logs
    emptyDir: {}
