apiVersion: v1
kind: Pod
metadata:
  labels:
    run: vol-pod
  name: vol-pod
spec:
  containers:
  - image: busybox
    name: writer
    command: ["/bin/sh", "-c", "while true; do date >> /data/date.txt; sleep 5; done"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    emptyDir: {}
