# Fix: schedule corrected to 5 fields (every 2 hours)
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lab09-cron
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: task
            image: busybox
            command: ["echo", "running"]
          restartPolicy: OnFailure
