# Fix: liveness probe port changed to 80
apiVersion: v1
kind: Pod
metadata:
  name: lab06-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 2
