# Fix: use networking.k8s.io/v1, add pathType and new backend format
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lab04-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: app.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web-svc
            port:
              number: 80
