# Bug: selector.matchLabels doesn't match template.metadata.labels
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab10-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx
