# Bug: restartPolicy is Always — not valid for Jobs (must be Never or OnFailure)
apiVersion: batch/v1
kind: Job
metadata:
  name: lab08-job
spec:
  template:
    spec:
      containers:
      - name: worker
        image: busybox
        command: ["echo", "done"]
      restartPolicy: Always
