# Bug: liveness probe checks port 3000 but app runs on port 80
apiVersion: v1
kind: Pod
metadata:
  name: lab06-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 3
      periodSeconds: 3
      failureThreshold: 2
