# Bug: service targetPort doesn't match container port
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab02-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab02
  template:
    metadata:
      labels:
        app: lab02
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lab02-svc
spec:
  selector:
    app: lab02
  ports:
  - port: 80
    targetPort: 8080
