# Bug: egress policy blocks DNS (port 53 UDP), so pod can't resolve any service names
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: lab11-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: restricted
  policyTypes:
  - Egress
  egress:
  - to: []
    ports:
    - port: 443
      protocol: TCP
