# LAB 01 SOLUTION
# BUG 1: label id: wrong-label  -> id: q02-pod
# BUG 2: container name: q02-pod -> main-container
---
apiVersion: v1
kind: Pod
metadata:
  name: q02-pod
  labels:
    id: q02-pod
spec:
  containers:
  - name: main-container
    image: nginx:1.21
