# LAB 03 SOLUTION
# BUG: type: Opaque -> type: kubernetes.io/service-account-token
# Also remove the fake stringData — Kubernetes populates the token automatically
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: q05-sa
  namespace: neptune
---
apiVersion: v1
kind: Secret
metadata:
  name: q05-token
  namespace: neptune
  annotations:
    kubernetes.io/service-account.name: q05-sa
type: kubernetes.io/service-account-token
