# LAB 02 SOLUTION
# BUG 1: parallelism: 5 -> 2
# BUG 2: label key "app" -> "id"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: q03-job
  namespace: neptune
spec:
  completions: 3
  parallelism: 2
  template:
    metadata:
      labels:
        id: q03-job
    spec:
      restartPolicy: Never
      containers:
      - name: job
        image: busybox
        command: ["/bin/sh", "-c", "sleep 2 && echo done"]
