# LAB 05 SOLUTION
# BUG: namespace: neptune -> pluto
---
apiVersion: v1
kind: Pod
metadata:
  name: q07-webserver
  namespace: pluto
  labels:
    app: webserver
spec:
  containers:
  - name: nginx
    image: nginx:1.21
    ports:
    - containerPort: 80
